package com.ibm.dsw.quote.draftquote.config;

import com.ibm.dsw.quote.base.config.StateKeys;



/**
 * Copyright 2006 by IBM Corporation All rights reserved.
 * 
 * This software is the confidential and proprietary information of IBM
 * Corporation. ("Confidential Information").
 * 
 * This <code>StateKeys<code> class .
 *    
 * @author: chenzhh@cn.ibm.com
 * Creation date: Apr 1, 2006
 */
public interface DraftQuoteStateKeys extends StateKeys{
    public static final String STATE_EMPTY_DRAFT_QUOTE_PP = "STATE_EMPTY_DRAFT_QUOTE_PP";

    public static final String STATE_DISPLAY_PARTS_PRICE_TAB = "STATE_DISPLAY_PARTS_PRICE_TAB";

    public static final String STATE_DISPLAY_PARTS_PRICING_PAPAE_TAB = "STATE_DISPLAY_PARTS_PRICING_PAPAE_TAB";

    public static final String STATE_DISPLAY_QUOTE_SUBMISSION = "STATE_DISPLAY_QUOTE_SUBMISSION";

    public static final String STATE_DISPLAY_PARTS_PRICING_PPSS_TAB = "STATE_DISPLAY_PARTS_PRICING_PPSS_TAB";

    public static final String STATE_DISPLAY_PARTS_PRICING_FCT_TAB = "STATE_DISPLAY_PARTS_PRICING_FCT_TAB";

    public static final String STATE_DRAFT_SQ_SALES_INFO_TAB = "STATE_DRAFT_SQ_SALES_INFO_TAB";
    
    public static final String STATE_DRAFT_RQ_SALES_INFO_TAB = "STATE_DRAFT_RQ_SALES_INFO_TAB";
    
    public static final String STATE_DISPLAY_SQ_CUST_PRTNR_TAB = "STATE_DISPLAY_SQ_CUST_PRTNR_TAB";
    
    public static final String STATE_DISPLAY_RQ_CUST_PRTNR_TAB = "STATE_DISPLAY_RQ_CUST_PRTNR_TAB";
    
    public static final String STATE_DISPLAY_EMPTY_DRAFT_QUOTE = "STATE_DISPLAY_EMPTY_DRAFT_QUOTE";
    
    public static final String STATE_SET_USER_COOKIE = "STATE_SET_USER_COOKIE";

    public static final String STATE_DISPLAY_SQ_SPECIAL_BID_TAB_PA_PAE = "STATE_DISPLAY_SQ_SPECIAL_BID_TAB_PA_PAE";
    
    public static final String STATE_DISPLAY_SQ_SPECIAL_BID_TAB_OEM = "STATE_DISPLAY_SQ_SPECIAL_BID_TAB_OEM";

    public static final String STATE_DISPLAY_RQ_SPECIAL_BID_TAB_PA_PAE = "STATE_DISPLAY_RQ_SPECIAL_BID_TAB_PA_PAE";

    public static final String STATE_DISPLAY_SQ_SPECIAL_BID_TAB_FCT = "STATE_DISPLAY_SQ_SPECIAL_BID_TAB_FCT";

    public static final String STATE_DISPLAY_SQ_SPECIAL_BID_TAB_PPSS = "STATE_DISPLAY_SQ_SPECIAL_BID_TAB_PPSS";

    public static final String STATE_DISPLAY_RQ_SPECIAL_BID_TAB_FCT = "STATE_DISPLAY_RQ_SPECIAL_BID_TAB_FCT";
    
    public static final String STATE_DISPLAY_SQ_SPECIAL_BID_TAB_SSP = "STATE_DISPLAY_SQ_SPECIAL_BID_TAB_SSP";
    
    public static final String STATE_DISPLAY_OVERRIDE_DATE_POPUP = "STATE_DISPLAY_OVERRIDE_DATE_POPUP";
    
    public static final String STATE_DISPLAY_RELATED_PARTS = "STATE_DISPLAY_RELATED_PARTS";

    public static final String STATE_DISPLAY_RQ_SPECIAL_BID_TAB_PPSS = "STATE_DISPLAY_RQ_SPECIAL_BID_TAB_PPSS";
    
    public static final String STATE_DISPLAY_REPLACEMENT_PARTS = "STATE_DISPLAY_REPLACEMENT_PARTS";
    
    public static final String STATE_DISPLAY_REPLACEMENT_PARTS_RENEWAL = "STATE_DISPLAY_REPLACEMENT_PARTS_RENEWAL";
    
    public static final String STATE_DISPLAY_REPLACEMENT_PARTS_SUBMITTED = "STATE_DISPLAY_REPLACEMENT_PARTS_SUBMITTED";

    public static final String STATE_DISPLAY_RQ_STATUS_TAB = "STATE_DISPLAY_RQ_STATUS_TAB";
    
    public static final String STATE_DISPLAY_QUOTE_CONFIRMATION = "STATE_DISPLAY_QUOTE_CONFIRMATION";

    public static final String STATE_DISPLAY_QUOTE_CONFIRMATION_READY_ORDER = "STATE_DISPLAY_QUOTE_CONFIRMATION_READY_ORDER";
    
    public static final String STATE_DISPLAY_RQ_PARTS_PRICING_PA_TAB = "STATE_DISPLAY_RQ_PARTS_PRICING_PA_TAB";
    
    public static final String STATE_DISPLAY_RQ_PARTS_PRICING_PAE_TAB = "STATE_DISPLAY_RQ_PARTS_PRICING_PAE_TAB";
    
    public static final String STATE_DISPLAY_RQ_PARTS_PRICING_FCT_TAB = "STATE_DISPLAY_RQ_PARTS_PRICING_FCT_TAB";
    
    public static final String STATE_DISPLAY_DRAFT_QUOTE = "STATE_DISPLAY_DRAFT_QUOTE";
    
    public static final String STATE_DISPLAY_SPECIALBID_FINALIZATION = "STATE_DISPLAY_SPECIALBID_FINALIZATION";
    
    public static final String STATE_DISPLAY_SPECIALBID_FINALIZATION_RESULT = "STATE_DISPLAY_SPECIALBID_FINALIZATION_RESULT";
    
    public static final String STATE_DISPLAY_ADD_ATTACHS_FOR_SALESINFO = "STATE_DISPLAY_ADD_ATTACHS_FOR_SALESINFO";
    
    public static final String STATE_DISPLAY_ADD_ATTACHS_INPUT_FOR_SALESINFO = "STATE_DISPLAY_ADD_ATTACHS_INPUT_FOR_SALESINFO";
    
    public static final String STATE_DISPLAY_ADD_ATTACHS_COMPLETE_FOR_SALESINFO = "STATE_DISPLAY_ADD_ATTACHS_COMPLETE_FOR_SALESINFO";
    
    public static final String STATE_DISPLAY_ASSGN_CRT_AGRMNT = "STATE_DISPLAY_ASSGN_CRT_AGRMNT";
    
    public static final String STATE_DISPLAY_PARTS_PRICING_OEM_TAB = "STATE_DISPLAY_PARTS_PRICING_OEM_TAB";
    
    public static final String STATE_DISPLAY_PARTS_PRICING_SSP_TAB = "STATE_DISPLAY_PARTS_PRICING_SSP_TAB";
    
    public static final String STATE_DISPLAY_RQ_PARTS_PRICING_OEM_TAB = "STATE_DISPLAY_RQ_PARTS_PRICING_OEM_TAB";  
    
    public static final String STATE_DISPLAY_LOCKED_QUOTE = "STATE_DISPLAY_LOCKED_QUOTE";   
    
    public static final String STATE_DISPLAY_OVERWRITTEN_QUOTE = "STATE_DISPLAY_OVERWRITTEN_QUOTE";
    
    public static final String STATE_NOT_MEET_BID_ITERATION = "STATE_NOT_MEET_BID_ITERATION";
    
    public static final String STATE_CUST_PRTNR_TAB_BID_ITERATION = "STATE_CUST_PRTNR_TAB_BID_ITERATION";
    
    public static final String STATE_SALES_INFO_TAB_BID_ITERATION = "STATE_SALES_INFO_TAB_BID_ITERATION";
    
    public static final String STATE_CREATE_FROM_ORDER_ERROR = "STATE_CREATE_FROM_ORDER_ERROR";

    public static final String STATE_DISPLAY_QT_AUDIT_HIST = "STATE_DISPLAY_QT_AUDIT_HIST";
    
    public static final String STATE_DISPLAY_MIGRATE_PART_LIST = "STATE_DISPLAY_MIGRATE_PART_LIST";
    
    public static final String STATE_FCT2PA_CUST_PARTNER = "STATE_FCT2PA_CUST_PARTNER";
    
    public static final String STATE_FCT2PA_CONFIRM_SCREEN = "STATE_MIGRATION_CONFIRM_SCREEN";
    
    public static final String STATE_FCT2PA_FAIL_SCREEN = "STATE_MIGRATION_FAIL_SCREEN";
    
    public static final String STATE_FCT2PA_MIGRATE_ERROR = "STATE_FCT2PA_MIGRATE_ERROR";

    public static final String STATE_RESUBMIT_MIGRATE_SCREEN = "STATE_RESUBMIT_MIGRATE_SCREEN";
    
    public static final String STATE_DISPLAY_RELATED_BIDS = "STATE_DISPLAY_RELATED_BIDS";
    
    public static final String STATE_DISPLAY_EVAL_QUOTE_UNDER_EVALUATION = "STATE_DISPLAY_EVAL_QUOTE_UNDER_EVALUATION";
   
    public static final String STATE_REDIRECT_TO_ADD_LPP_FORM = "STATE_REDIRECT_TO_ADD_LPP_FORM";
    public static final String STATE_REDIRECT_TO_ADD_PRIOR_PRICE_FORM = "STATE_REDIRECT_TO_ADD_PRIOR_PRICE_FORM";
    
    public static final String STATE_REDIRECT_TO_VIEW_UPDATE_LPP_FORM = "STATE_REDIRECT_TO_VIEW_UPDATE_LPP_FORM";
    
    public static final String STATE_REDIRECT_TO_VIEW_UPDATE_OMITTED_LPP_FORM = "STATE_REDIRECT_TO_VIEW_UPDATE_OMITTED_LPP_FORM";
    
    public static final String STATE_REDIRECT_TO_SUBMIT_LPP_FORM = "STATE_REDIRECT_TO_SUBMIT_LPP_FORM";
    
    public static final String STATE_DISPLAY_CREATE_APPLIANCE_ADDRESS = "STATE_DISPLAY_CREATE_APPLIANCE_ADDRESS";
    
    public static final String STATE_DISPLAY_SUBMITTEDQT_CREATE_APPLIANCE_ADDRESS = "STATE_DISPLAY_SUBMITTEDQT_CREATE_APPLIANCE_ADDRESS";
    
    public static final String STATE_DISPLAY_OMITTED_LINEITEM_LIST = "STATE_DISPLAY_OMITTED_LINEITEM_LIST";
    
    public static final String STATE_DISPLAY_SUBMITTED_OMITTED_LINEITEM_LIST = "STATE_DISPLAY_SUBMITTED_OMITTED_LINEITEM_LIST";
    
    public static final String STATE_DISPLAY_DRAFT_TOU_LIST = "STATE_DISPLAY_DRAFT_TOU_LIST";
    
    //public static final String STATE_REDIRECT_TO_VIEW_OMITTED_UPDATE_LPP_FORM = "STATE_REDIRECT_TO_VIEW_OMITTED_UPDATE_LPP_FORM";
    
    public static final String STATE_REDIRECT_TO_SUBMIT_OMITTED_LPP_FORM = "STATE_REDIRECT_TO_SUBMIT_OMITTED_LPP_FORM";
}
