package com.ibm.dsw.quote.findquote.config;

/**
 * Copyright 2007 by IBM Corporation All rights reserved.
 * 
 * This software is the confidential and proprietary information of IBM
 * Corporation. ("Confidential Information").
 * 
 * The <code>FindQuoteStateKeys</code> class.
 * 
 * @author wangxu@cn.ibm.com
 *
 * Created on 2007-4-27
 */
public interface FindQuoteStateKeys {
    
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_IBMER = "STATE_DISPLAY_FIND_QUOTE_BY_IBMER";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_CUSTOMER = "STATE_DISPLAY_FIND_QUOTE_BY_CUSTOMER";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_PARTNER = "STATE_DISPLAY_FIND_QUOTE_BY_PARTNER";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_COUNTRY = "STATE_DISPLAY_FIND_QUOTE_BY_COUNTRY";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_APPVLATTR = "STATE_DISPLAY_FIND_QUOTE_BY_APPVLATTR";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_NUM = "STATE_DISPLAY_FIND_QUOTE_BY_NUM";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_SIEBEL_NUM = "STATE_DISPLAY_FIND_QUOTE_BY_SIEBEL_NUM";
    public static final String STATE_DISPLAY_FIND_QUOTE_BY_ORDER_NUM = "STATE_DISPLAY_FIND_QUOTE_BY_ORDER_NUM";
    public static final String STATE_DISPLAY_STATUS_TRACKER_SETTINGS = "STATE_DISPLAY_STATUS_TRACKER_SETTINGS";

    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_IBMER = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_IBMER";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_CUSTOMER = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_CUSTOMER";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_PARTNER = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_PARTNER";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_COUNTRY = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_COUNTRY";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_NUM = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_NUM";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_SIEBEL_NUM = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_SIEBEL_NUM";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_ORDER_NUM = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_ORDER_NUM";
    public static final String STATE_DISPLAY_STATUS_TRACKER = "STATE_DISPLAY_STATUS_TRACKER";
    public static final String STATE_DISPLAY_APPROVAL_QUEUE_TRACKER = "STATE_DISPLAY_APPROVAL_QUEUE_TRACKER";
    public static final String STATE_ALTER_DISPLAY_FIND_BY_COUNTRY = "STATE_ALTER_DISPLAY_FIND_BY_COUNTRY";
    public static final String STATE_DISPLAY_APPROVAL_QUEUE = "STATE_DISPLAY_APPROVAL_QUEUE";
    public static final String STATE_DISPLAY_EVALUATOR_QUEUE = "STATE_DISPLAY_EVALUATOR_QUEUE";
    
    public static final String STATE_ALTER_DISPLAY_FIND_BY_APPVLATTR = "STATE_ALTER_DISPLAY_FIND_BY_APPVLATTR";
    public static final String STATE_DISPLAY_FIND_QUOTE_RESULT_BY_APPVLATTR = "STATE_DISPLAY_FIND_QUOTE_RESULT_BY_APPVLATTR";
}
