package com.ibm.dsw.quote.newquote.spreadsheet;

/**
 * Copyright 2007 by IBM Corporation All rights reserved.
 * 
 * This software is the confidential and proprietary information of IBM
 * Corporation. ("Confidential Information").
 * 
 * This <code>NativeExcelAdapterForFCT<code> class.
 *    
 * @author: zhaoxw@cn.ibm.com
 * 
 * Creation date: Mar 18, 2010
 */

public class NativeExcelAdapterForFCT extends NativeExcelAdapter {
    {
        //exported part cell position
    	PART_COL_IND_PART_NUMBER = 0;
    	PART_COL_IND_PART_DESCRIPTION = 1;
    	PART_COL_IND_QUANTITY = 2;
    	PART_COL_IND_ADD_YEARS = 3;
    	PART_COL_IND_STANDARD_START_DATE_FORMULA = 4;
    	PART_COL_IND_STANDARD_END_DATE_FORMULA = 5;
    	PART_COL_IND_OVERRIDE_START_DATE = 6;
    	PART_COL_IND_OVERRIDE_END_DATE = 7;
    	PART_COL_IND_ENTITLED_UNIT_PRICE_FORMULA = 8;
    	PART_COL_IND_OVERRIDE_PRICE = 9;
    	PART_COL_IND_DISCOUNT_PERCENT = 10;
    	PART_COL_IND_BID_UNIT_PRICE_FORMULA = 11;
    	PART_COL_IND_ENTITLED_EXTENDED_PRICE_FORMULA = 12;
    	PART_COL_IND_BID_EXTENDED_PRICE_FORMULA = 13;
    	
    	PART_COL_IND_X_FORMULA = 14;
    	PART_COL_IND_RENEWAL_QUOTE_LINE_ITEM_NUMBER = 15;
    	PART_COL_IND_SORT_SEQ_NUM = 16;
    	PART_COL_IND_ADDITIONAL_YEAR_COVERAGE_SEQ_NUM = 17;
    	PART_COL_IND_HIDDEN_TOTAL_PRICE = 19;
    	PART_COL_IND_HIDDEN_QUANTITY = 20;
    	PART_COL_IND_HIDDEN_OVERRIDE_START_DATE = 21;
    	PART_COL_IND_HIDDEN_OVERRIDE_END_DATE = 22;
    	PART_COL_IND_HIDDEN_OVERRIDE_PRICE = 23;
    	PART_COL_IND_HIDDEN_DISCOUNT_PERCENT = 24;
    	PART_COL_IND_CHANGED_FLAG_FORMULA = 25;
    	PART_COL_IND_HIDDEN_STANDARD_START_DATE = 26;
    	PART_COL_IND_HIDDEN_BID_UNIT_PRICE = 27;
    	PART_COL_IND_HIDDEN_ENTITLED_EXT_PRICE = 28;
    	PART_COL_IND_BID_UNIT_PRICE_DECIMAL_4 = 29;
    	PART_COL_IND_OVERRIDE_PRICE_DECIMAL_4 = 29;
    	
    	// additional part cell position
    	ADD_PART_COL_IND_PART_NUMBER = 0;
    	ADD_PART_COL_IND_PART_DESCRIPTION = 1;
    	ADD_PART_COL_IND_QUANTITY = 2;
    	ADD_PART_COL_IND_ADD_YEARS = 3;
    	ADD_PART_COL_IND_STANDARD_START_DATE_FORMULA = 4;
    	ADD_PART_COL_IND_STANDARD_END_DATE_FORMULA = 5;
    	ADD_PART_COL_IND_OVERRIDE_START_DATE = 6;
    	ADD_PART_COL_IND_OVERRIDE_END_DATE = 7;
    	ADD_PART_COL_IND_ENTITLED_UNIT_PRICE = 8;
    	ADD_PART_COL_IND_OVERRIDE_PRICE = 9;
    	ADD_PART_COL_IND_DISCOUNT_PERCENT = 10;
    	
    	// exported saas part cell position
    	SAASPART_COL_IND_ENTITLED_RATE = 9;
        SAASPART_COL_IND_BID_RATE = 10;
        SAASPART_COL_IND_ENTITLED_TCV = 11;
    	SAASPART_COL_IND_OVERRIDE_PRICE = 12;
        SAASPART_COL_IND_DISCOUNT_PERCENT = 13;
        SAASPART_COL_IND_BID_TCV = 14;
        SAASPART_COL_IND_BP_DISCOUNT = 15;
        SAASPART_COL_IND_BP_TCV_SUBMIT = 16;
        SAASPART_COL_IND_BP_TCV = 17;
        
    	/*//exported saas part cell position for submitted
    	SAASPART_COL_IND_ENTITLED_TCV_FORMULA = 10;
    	SAASPART_COL_IND_DISCOUNT_PERCENT_SUBMIT = 11;
    	SAASPART_COL_IND_BID_TCV_SUBMIT = 12;
    	SAASPART_COL_IND_BID_TCV_FORMULA = 12;
    	SAASPART_COL_IND_BP_DISCOUNT_SUBMIT = 13;
    	SAASPART_COL_IND_BP_OVERRIDE_DISCOUNT_SUBMIT = 14;
    	SAASPART_COL_IND_BP_OVERRIDE_DISCOUNT = 15;
    	SAASPART_COL_IND_BP_TCV_FORMULA = 15;*/
    }
}
