package com.ibm.dsw.quote.newquote.spreadsheet;

/**
 * Copyright 2007 by IBM Corporation All rights reserved.
 * 
 * This software is the confidential and proprietary information of IBM
 * Corporation. ("Confidential Information").
 * 
 * This <code>NativeExcelAdapterForPA<code> class.
 *    
 * @author: zhaoxw@cn.ibm.com
 * 
 * Creation date: Mar 18, 2010
 */

public class NativeExcelAdapterForFCT2PA extends NativeExcelAdapter {
	public NativeExcelAdapterForFCT2PA(){
		 // exported part cell position
		PART_COL_IND_PART_NUMBER = 0;
		PART_COL_IND_PART_DESCRIPTION = 1;
		PART_COL_IND_RESELLER_AUTHORIZATION = 2;
		PART_COL_IND_RESELLER_AUTHORIZATION_TERMS = 3;
		PART_COL_IND_QUANTITY = 4;
		PART_COL_IND_PRORATE= 5;
		PART_COL_IND_ADD_YEARS = 6;
		PART_COL_IND_STANDARD_START_DATE_FORMULA = 7;
		PART_COL_IND_STANDARD_END_DATE_FORMULA = 8;
		PART_COL_IND_OVERRIDE_START_DATE = 9;
		PART_COL_IND_OVERRIDE_END_DATE = 10;
		PART_COL_IND_RENEWAL_QUOTE_NUMBER = 11;
		PART_COL_IND_ITEM_POINTS = 12;
		PART_COL_IND_ENTITLED_UNIT_PRICE_FORMULA = 13;
		PART_COL_IND_OVERRIDE_PRICE = 14;
		PART_COL_IND_DISCOUNT_PERCENT = 15;
		PART_COL_IND_TOTAL_POINTS_FORMULA = 16;
		PART_COL_IND_BID_UNIT_PRICE_FORMULA = 17;
		PART_COL_IND_ENTITLED_EXTENDED_PRICE_FORMULA = 18;
		PART_COL_IND_BID_EXTENDED_PRICE_FORMULA = 19;
		PART_COL_IND_BP_DISCOUNT = 20;
		PART_COL_IND_BP_OVERRIDE_DISCOUNT = 21;
		PART_COL_IND_BP_EXTENDED_PRICE_FORMULA = 22;	
		PART_COL_IND_X_FORMULA = 23;
		PART_COL_IND_RENEWAL_QUOTE_LINE_ITEM_NUMBER = 24;
		PART_COL_IND_SORT_SEQ_NUM = 25;
		PART_COL_IND_ADDITIONAL_YEAR_COVERAGE_SEQ_NUM = 26;
		PART_COL_IND_HIDDEN_TOTAL_PRICE = 28;
		PART_COL_IND_HIDDEN_QUANTITY = 29;
		PART_COL_IND_HIDDEN_OVERRIDE_START_DATE = 30;
		PART_COL_IND_HIDDEN_OVERRIDE_END_DATE = 31;
		PART_COL_IND_HIDDEN_OVERRIDE_PRICE = 32;
		PART_COL_IND_HIDDEN_DISCOUNT_PERCENT = 33;
		PART_COL_IND_CHANGED_FLAG_FORMULA = 34;
		PART_COL_IND_HIDDEN_STANDARD_START_DATE = 35;
		PART_COL_IND_HIDDEN_BID_UNIT_PRICE = 36;
		PART_COL_IND_HIDDEN_ENTITLED_EXT_PRICE = 37;
		PART_COL_IND_HIDDEN_ENTITLED_UNIT_PRICE = 38;
		PART_COL_IND_HIDDEN_BP_EXTENDED_PRICE = 39;
		PART_COL_IND_HIDDEN_BP_OVERRIDE_DISCOUNT = 40;
		
		PART_COL_IND_BID_UNIT_PRICE_DECIMAL_4 = 42;
		PART_COL_IND_OVERRIDE_PRICE_DECIMAL_4 = 42;
		PART_ROW_IND_OVERRIDE_PRICE_DECIMAL_4 = 0;
		
		// pricing support data cell position
		PRICING_SUPPORT_COL_IND_PART_NUMBER = 0;
		PRICING_SUPPORT_COL_IND_REVENUE_STREAM = 1;
		PRICING_SUPPORT_COL_A = 2;
		PRICING_SUPPORT_COL_B = 3;
		PRICING_SUPPORT_COL_D = 4;
		PRICING_SUPPORT_COL_E = 5;
		PRICING_SUPPORT_COL_F = 6;
		PRICING_SUPPORT_COL_G = 7;
		PRICING_SUPPORT_COL_H = 8;
		PRICING_SUPPORT_COL_I = 9;
		PRICING_SUPPORT_COL_J = 10;
		PRICING_SUPPORT_COL_GV = 11;
		PRICING_SUPPORT_COL_ED = 12;
		PRICING_SUPPORT_COL_NA = 13;	
		PRICING_SUPPORT_FIRST_COL = 'A';
		PRICING_SUPPORT_LAST_COL = 'N';
		
		// additional part cell position
		ADD_PART_COL_IND_PART_NUMBER = 0;
		ADD_PART_COL_IND_PART_DESCRIPTION = 1;
		ADD_PART_COL_IND_QUANTITY = 2;
		ADD_PART_COL_IND_PRORATE = 3;
		ADD_PART_COL_IND_ADD_YEARS = 4;
		ADD_PART_COL_IND_STANDARD_START_DATE_FORMULA = 5;
		ADD_PART_COL_IND_STANDARD_END_DATE_FORMULA = 6;
		ADD_PART_COL_IND_OVERRIDE_START_DATE = 7;
		ADD_PART_COL_IND_OVERRIDE_END_DATE = 8;
		ADD_PART_COL_IND_ITEM_POINTS = 9;
		ADD_PART_COL_IND_ENTITLED_UNIT_PRICE = 10;
		ADD_PART_COL_IND_OVERRIDE_PRICE = 11;
		ADD_PART_COL_IND_DISCOUNT_PERCENT = 12;
	    
	    // exported saas part cell position
	    SAASPART_COL_IND_PART_NUMBER = 0;
		SAASPART_COL_IND_PART_DESCRIPTION = 1;
		SAASPART_COL_IND_CONFIG_ID = 2;
		SAASPART_COL_IND_REPLACE_PART = 3;
		SAASPART_COL_IND_Ramp_Up_Period =4;
		SAASPART_COL_IND_MIGRATED_PART = 5;
	    SAASPART_COL_IND_QUANTITY = 6;
	    SAASPART_COL_IND_TERM = 7;
	    SAASPART_COL_IND_BILLING_FREQUENCY = 8;
	    SAASPART_COL_IND_TOTAL_POINTS = 9;
	    SAASPART_COL_IND_ENTITLED_RATE = 10;
	    SAASPART_COL_IND_BID_RATE = 11;
	    SAASPART_COL_IND_ENTITLED_TCV = 12;
	    SAASPART_COL_IND_OVERRIDE_PRICE = 13;
	    SAASPART_COL_IND_DISCOUNT_PERCENT = 14;
	    SAASPART_COL_IND_BID_TCV = 15;
	    SAASPART_COL_IND_BP_DISCOUNT = 16;
	    SAASPART_COL_IND_BP_OVERRIDE_DISCOUNT = 17;
	    SAASPART_COL_IND_BP_RATE = 18;
	    SAASPART_COL_IND_BP_TCV = 19;
	    
	    SAASPART_COL_IND_HIDDEN_TERM = 21;
	    SAASPART_COL_IND_HIDDEN_QUANTITY = 22;
	    SAASPART_COL_IND_HIDDEN_ENTITLED_TCV = 23;
	    SAASPART_COL_IND_HIDDEN_BID_TCV = 24;
	    SAASPART_COL_IND_HIDDEN_BP_TCV = 25;
	    SAASPART_COL_IND_HIDDEN_BILLING_FREQUENCY = 26;
	    SAASPART_COL_IND_HIDDEN_SUP = 27;
	    SAASPART_COL_IND_HIDDEN_UNIT_POINTS = 28;
	    SAASPART_COL_IND_HIDDEN_SHOW_QTY = 29;
	    SAASPART_COL_IND_HIDDEN_SHOW_TOTALPOINTS = 30;
	    SAASPART_COL_IND_HIDDEN_SHOW_ENTITLETCV = 31;
	    SAASPART_COL_IND_HIDDEN_SHOW_BIDTCV = 32;
	    SAASPART_COL_IND_HIDDEN_SHOW_BPTCV = 33;
	    SAASPART_COL_IND_HIDDEN_IS_SETUP=34;
	    SAASPART_COL_IND_HIDDEN_IS_PRODHUMANSERVICE=35;
	    SAASPART_COL_IND_HIDDEN_IS_SUBSCRPTN=36;
	    SAASPART_COL_IND_HIDDEN_IS_SHOW_TERM=37;
	    SAASPART_COL_IND_HIDDEN_OVERRIDE_PRICE=38;
	    SAASPART_COL_IND_HIDDEN_OVERRIDE_DISCOUNT=39;
	    SAASPART_COL_IND_HIDDEN_BPOVERRIDEDISCOUNT=40;
	    SAASPART_COL_IND_HIDDEN_IS_NOT_CHANGED=41;
	    
	    SAASPART_COL_IND_HIDDEN_REF_DOC_NUM=42;
	    SAASPART_COL_IND_HIDDEN_ERROR_CODE=43;
	    SAASPART_COL_IND_HIDDEN_CONFIGRTN_ACTION=44;
	    SAASPART_COL_IND_HIDDEN_ENDDATE=45;
	    SAASPART_COL_IND_HIDDEN_COTERM_TO_CONFIGRTNID=46;
	    SAASPART_COL_IND_HIDDEN_OVERRIDE_FLAG=47;
	    SAASPART_COL_IND_HIDDEN_CONFIGRTRCONFIGRTNID = 48;
	    SAASPART_COL_IND_HIDDEN_BRAND_CODE = 49;
	    SAASPART_COL_IND_HIDDEN_IS_DECIMAL4_FLAG = 50;
	    SAASPART_COL_IND_HIDDEN_LOCAL_UNIT_PRICE_FORMULA = 51;
	    SAASPART_COL_IND_HIDDEN_BILLING_FREQUENCY_FOR_RATE = 52;
	    SAASPART_COL_IND_HIDDEN_QUANTITY_FOR_RATE = 53;
	    SAASPART_COL_IND_HIDDEN_IS_SUBSCRPTN_OVRAGE = 54;
	    SAASPART_COL_IND_HIDDEN_DEST_SEQ_NUM = 55;
	    SAASPART_COL_IND_HIDDEN_RELATED_LINEITM_NUM = 56;
	    SAASPART_COL_IND_HIDDEN_IS_RAMPUP_PART = 57;
	    SAASPART_COL_IND_HIDDEN_PROVISIONING_ID = 58;
	    
	    //for saas additional sheet
	    ADD_SAASPART_COL_IND_PART_NUMBER = 0;
	    ADD_PART_COL_IND_MIGRATED_PART = 2;
	    ADD_SAASPART_COL_IND_QUANTITY = 3;
	    ADD_SAASPART_COL_IND_TERM = 4;
	    ADD_SAASPART_COL_IND_BILLING_FREQUENCY = 5;
	    ADD_SAASPART_COL_IND_ENTITLED_RATE = 6;
	    ADD_SAASPART_COL_IND_BID_RATE = 7;
	    ADD_SAASPART_COL_IND_OVERRIDE_PRICE = 9;
	    ADD_SAASPART_COL_IND_DISCOUNT_PERCENT = 10;
	    
	    //exported saas part cell position for submitted
	    SAASPART_COL_IND_MIGRATED_PART_SUBMIT = 5;
	    SAASPART_COL_IND_QUANTITY_SUBMIT = 6;
	    SAASPART_COL_IND_TERM_SUBMIT = 7;
	    SAASPART_COL_IND_BILLING_FREQUENCY_SUBMIT = 8;
	    SAASPART_COL_IND_ENTITLED_RATE_SUBMIT = 9;
	    SAASPART_COL_IND_BID_RATE_SUBMIT = 10;
		SAASPART_COL_IND_TOTAL_POINTS_SUBMIT = 11; 
		SAASPART_COL_IND_ENTITLED_TCV_SUBMIT = 12;
		SAASPART_COL_IND_DISCOUNT_PERCENT_SUBMIT = 13;
		SAASPART_COL_IND_BID_TCV_SUBMIT = 14;
		SAASPART_COL_IND_BID_TCV_FORMULA = 14;
		SAASPART_COL_IND_BP_DISCOUNT_SUBMIT = 15;
		SAASPART_COL_IND_BP_OVERRIDE_DISCOUNT_SUBMIT = 16;
		SAASPART_COL_IND_BP_TCV_SUBMIT = 17;
		SAASPART_COL_IND_BP_TCV_FORMULA = 17;
	}
	
}
