package com.ibm.dsw.quote.newquote.spreadsheet;

/**
 * Copyright 2007 by IBM Corporation All rights reserved.
 * 
 * This software is the confidential and proprietary information of IBM
 * Corporation. ("Confidential Information").
 * 
 * This <code>NativeExcelAdapterForPAE<code> class.
 *    
 * @author: zhaoxw@cn.ibm.com
 * 
 * Creation date: Mar 18, 2010
 */

public class NativeExcelAdapterForPAEOld extends NativeExcelAdapter {
    {
//      exported part cell position
        PART_COL_IND_PART_NUMBER = 0;
        PART_COL_IND_PART_DESCRIPTION = 1;
        PART_COL_IND_RESELLER_AUTHORIZATION = 2;
        PART_COL_IND_RESELLER_AUTHORIZATION_TERMS = 3;
        PART_COL_IND_QUANTITY = 4;
        PART_COL_IND_ADD_YEARS = 5;
        PART_COL_IND_STANDARD_START_DATE_FORMULA = 6;
        PART_COL_IND_STANDARD_END_DATE_FORMULA = 7;
        PART_COL_IND_OVERRIDE_START_DATE = 8;
        PART_COL_IND_OVERRIDE_END_DATE = 9;
        PART_COL_IND_RENEWAL_QUOTE_NUMBER = 10;
        PART_COL_IND_ENTITLED_UNIT_PRICE_FORMULA = 11;
        PART_COL_IND_OVERRIDE_PRICE = 12;
        PART_COL_IND_DISCOUNT_PERCENT = 13;
        PART_COL_IND_BID_UNIT_PRICE_FORMULA = 14;
        PART_COL_IND_ENTITLED_EXTENDED_PRICE_FORMULA = 15;
        PART_COL_IND_BID_EXTENDED_PRICE_FORMULA = 16;
        PART_COL_IND_BP_DISCOUNT = 17;
        PART_COL_IND_BP_OVERRIDE_DISCOUNT = 18;
        PART_COL_IND_BP_EXTENDED_PRICE_FORMULA = 19;
        PART_COL_IND_X_FORMULA = 20;
        PART_COL_IND_RENEWAL_QUOTE_LINE_ITEM_NUMBER = 21;
        PART_COL_IND_SORT_SEQ_NUM = 22;
        PART_COL_IND_ADDITIONAL_YEAR_COVERAGE_SEQ_NUM = 23;
        PART_COL_IND_HIDDEN_TOTAL_PRICE = 25;
        PART_COL_IND_HIDDEN_QUANTITY = 26;
    	PART_COL_IND_HIDDEN_OVERRIDE_START_DATE = 27;
    	PART_COL_IND_HIDDEN_OVERRIDE_END_DATE = 28;
        PART_COL_IND_HIDDEN_OVERRIDE_PRICE = 29;
        PART_COL_IND_HIDDEN_DISCOUNT_PERCENT = 30;
        PART_COL_IND_CHANGED_FLAG_FORMULA = 31;
        PART_COL_IND_HIDDEN_STANDARD_START_DATE = 32;
        PART_COL_IND_HIDDEN_BID_UNIT_PRICE = 33;
        PART_COL_IND_HIDDEN_ENTITLED_EXT_PRICE = 34;
    	PART_COL_IND_BID_UNIT_PRICE_DECIMAL_4 = 36;
    	PART_COL_IND_OVERRIDE_PRICE_DECIMAL_4 = 36;
        
    	// additional part cell position
    	ADD_PART_COL_IND_PART_NUMBER = 0;
    	ADD_PART_COL_IND_PART_DESCRIPTION = 1;
    	ADD_PART_COL_IND_QUANTITY = 2;
    	ADD_PART_COL_IND_ADD_YEARS = 3;
    	ADD_PART_COL_IND_STANDARD_START_DATE_FORMULA = 4;
    	ADD_PART_COL_IND_STANDARD_END_DATE_FORMULA = 5;
    	ADD_PART_COL_IND_OVERRIDE_START_DATE = 6;
    	ADD_PART_COL_IND_OVERRIDE_END_DATE = 7;
    	ADD_PART_COL_IND_ENTITLED_UNIT_PRICE = 8;
    	ADD_PART_COL_IND_OVERRIDE_PRICE = 9;
    	ADD_PART_COL_IND_DISCOUNT_PERCENT = 10;
    }
}
